[package]
name = "walrus_dep"
edition = "2024.beta"

[dependencies]
Walrus = { git = "https://github.com/MystenLabs/walrus.git", rev = "testnet", subdir = "testnet-contracts/walrus" }

[addresses]
walrus_dep = "0x0"